- proarc-webapp/src/main/java/cz/cas/lib/proarc/webapp/client/widget/mods/NdkCartographicForm.java
- proarc-webapp/src/main/java/cz/cas/lib/proarc/webapp/client/widget/mods/NdkMonographVolumeForm.java
- proarc-webapp/src/main/java/cz/cas/lib/proarc/webapp/client/widget/mods/NdkPeriodicalForm.java
- proarc-webapp/src/main/java/cz/cas/lib/proarc/webapp/client/widget/mods/NdkSheetMusicForm.java
- proarc-webapp/src/main/java/cz/cas/lib/proarc/webapp/client/widget/mods/oldprint/OldPrintVolumeForm.java
Opravena položka jazyku katalogizace na "nepovinné".
>  issue #485: fix Language of Cataloging - R to be not mandatory

- proarc-common/src/main/java/cz/cas/lib/proarc/common/imports/TiffImporter.java
Changed reported filename from plainOcr to alto.
> issue #523: Error message Missing ALTO fixed

- README
- pom.xml
Update SmartGwt na 20161023, protože 20161020 byl smazán.
> issue #522: changed SmartGwt version

- .gitignore
ignoring idea directory + idea project files
> Added ignore rules for Idea IDE

- proarc-common/src/main/java/cz/cas/lib/proarc/common/object/oldprint/OldPrintMapperFactory.java
- proarc-common/src/main/java/cz/cas/lib/proarc/common/object/oldprint/OldPrintMonographTitleMapper.java
- proarc-common/src/main/java/cz/cas/lib/proarc/common/object/oldprint/OldPrintPlugin.java
- proarc-common/src/main/resources/metamodel/model_oldprintmonographtitle.xml
- proarc-webapp/src/main/java/cz/cas/lib/proarc/webapp/client/widget/mods/oldprint/OldPrintForms.java
- proarc-webapp/src/main/java/cz/cas/lib/proarc/webapp/client/widget/mods/oldprint/OldPrintMonographTitleForm.java
Cloned NDK Monograph Title for old print variant.
> issue #430: Old Print Monograph Title

- proarc-webapp/src/main/java/cz/cas/lib/proarc/webapp/client/action/TreeExpandAction.java
- proarc-webapp/src/main/java/cz/cas/lib/proarc/webapp/client/presenter/DigitalObjectManager.java
- proarc-webapp/src/main/java/cz/cas/lib/proarc/webapp/client/widget/DigitalObjectTreeView.java
- proarc-webapp/src/main/resources/cz/cas/lib/proarc/webapp/client/ClientMessages.properties
- proarc-webapp/src/main/resources/cz/cas/lib/proarc/webapp/client/ClientMessages_cs.properties
Nodes within Digital Object Manager can be recursively expanded.
> issue #229: Expanding tree nodes

- proarc-webapp/src/main/java/cz/cas/lib/proarc/webapp/client/ds/StreamProfileDataSource.java
- proarc-webapp/src/main/java/cz/cas/lib/proarc/webapp/client/presenter/DigitalObjectEditor.java
- proarc-webapp/src/main/java/cz/cas/lib/proarc/webapp/client/widget/ImportBatchItemEditor.java
- proarc-webapp/src/main/java/cz/cas/lib/proarc/webapp/client/widget/MediaEditor.java
Changed order of templates, first being the default profile to be
loaded.
> issue #427: Default image in doEditor

- proarc-common/src/main/java/cz/cas/lib/proarc/common/export/mets/structure/MetsElementVisitor.java
- proarc-common/src/test/java/cz/cas/lib/proarc/common/export/mets/MetsUtilsTest.java
- proarc-common/src/test/resources/cz/cas/lib/proarc/common/export/mets/periodikum/2ad73397-ef9d-429a-b3a5-65083fa4c333.xml
add a title of the periodical to the label (in NDK PSP export) https://github.com/proarc/proarc/issues/516
Title se do labelu přidává, jen pokud jde o periodikum, jinak ne. Současné testy fungují a přidán test chybějící hodnoty v labelu.
> issue #516: add title to label

- proarc-common/pom.xml
- proarc-common/src/main/java/cz/cas/lib/proarc/common/dao/empiredb/EmpireWorkflowJobDao.java
- proarc-common/src/main/java/cz/cas/lib/proarc/common/dao/empiredb/EmpireWorkflowMaterialDao.java
- proarc-common/src/main/java/cz/cas/lib/proarc/common/object/DigitalObjectManager.java
- proarc-common/src/main/java/cz/cas/lib/proarc/common/workflow/WorkflowManager.java
- proarc-common/src/main/java/cz/cas/lib/proarc/common/workflow/model/MaterialFilter.java
- proarc-common/src/main/java/cz/cas/lib/proarc/common/workflow/model/WorkflowModelConsts.java
- proarc-common/src/main/java/cz/cas/lib/proarc/common/workflow/profile/DisplayableType.java
- proarc-common/src/main/java/cz/cas/lib/proarc/common/workflow/profile/IDisplayableType.java
- proarc-common/src/main/java/cz/cas/lib/proarc/common/workflow/profile/JobDefinition.java
- proarc-common/src/main/java/cz/cas/lib/proarc/common/workflow/profile/JobDefinitionView.java
- proarc-common/src/main/java/cz/cas/lib/proarc/common/workflow/profile/ModelDefinition.java
- proarc-common/src/main/java/cz/cas/lib/proarc/common/workflow/profile/WorkflowItemView.java
- proarc-common/src/main/java/cz/cas/lib/proarc/common/workflow/profile/WorkflowProfileConsts.java
- proarc-common/src/main/resources/cz/cas/lib/proarc/common/workflow/profile/workflow.xsd
- proarc-common/src/test/java/cz/cas/lib/proarc/common/dao/empiredb/EmpireWorkflowMaterialDaoTest.java
- proarc-webapp/src/main/java/cz/cas/lib/proarc/webapp/client/ds/DigitalObjectDataSource.java
- proarc-webapp/src/main/java/cz/cas/lib/proarc/webapp/client/ds/WorkflowProfileDataSource.java
- proarc-webapp/src/main/java/cz/cas/lib/proarc/webapp/client/presenter/DigitalObjectCreator.java
- proarc-webapp/src/main/java/cz/cas/lib/proarc/webapp/client/widget/workflow/WorkflowJobView.java
- proarc-webapp/src/main/java/cz/cas/lib/proarc/webapp/server/rest/DigitalObjectResource.java
- proarc-webapp/src/main/java/cz/cas/lib/proarc/webapp/server/rest/RestException.java
- proarc-webapp/src/main/java/cz/cas/lib/proarc/webapp/server/rest/WorkflowResource.java
- proarc-webapp/src/main/java/cz/cas/lib/proarc/webapp/shared/rest/DigitalObjectResourceApi.java
Umožňuje vytváření digitálního objektů z obrazovky záměry. Je možné otestovat např. s tímto definičním souborem https://gist.github.com/MartinRumanek/1763e83f0b7b826d1f02a0c5cab8f027#file-workflow-xml.
Ještě je nutné
> issue #577: create object from rdflow

- proarc-common/src/main/java/cz/cas/lib/proarc/common/catalog/AlephXServer.java
- proarc-common/src/main/java/cz/cas/lib/proarc/common/config/CatalogConfiguration.java
- proarc-common/src/test/java/cz/cas/lib/proarc/common/catalog/AlephXServerTest.java
Disabling custom fields within .cfg file does not set null values.
> AlephXServer: Modifying config file null values

- proarc-common/src/main/java/cz/cas/lib/proarc/common/object/ndk/RdaRules.java
- proarc-common/src/test/resources/cz/cas/lib/proarc/common/xml/alephXServerDetailResponseAsMods.xml
Opraven test transformační šablony
> issue #603: repair test

- proarc-common/src/main/java/cz/cas/lib/proarc/common/mods/ndk/NdkPageMapper.java
- proarc-common/src/main/java/cz/cas/lib/proarc/common/object/ndk/NdkMetadataHandler.java
- proarc-common/src/test/java/cz/cas/lib/proarc/common/mods/ndk/NdkPageMapperTest.java
updating metadata from front-end does not add pageType for NormalPage
> issue #458: normalPage should not be stored

- proarc-common/src/main/java/cz/cas/lib/proarc/common/imports/TiffAsJp2Importer.java
- proarc-common/src/main/java/cz/cas/lib/proarc/common/imports/TiffAsJpegImporter.java
- proarc-common/src/test/java/cz/cas/lib/proarc/common/imports/TiffAsJp2ImporterTest.java
- proarc-common/src/test/java/cz/cas/lib/proarc/common/imports/TiffAsJpegImporterTest.java
+ added tests for consuming sets without specified image
> issue #599: Added type-check before JP2/JPG consume

- proarc-webapp/src/main/java/cz/cas/lib/proarc/webapp/client/widget/mods/NdkMonographTitleForm.java
Přidán element eventType do formuláře modelu Ndk Vícedílná monografie.
> issue #611: add eventType to model NdkMonographTitle

- proarc-webapp/src/main/java/cz/cas/lib/proarc/webapp/client/widget/mods/bdm/BornDigitalArticleForm.java
- proarc-webapp/src/main/java/cz/cas/lib/proarc/webapp/client/widget/mods/bdm/SimpleCejshArticleForm.java
Oprava povinnosti u elementu Subtitle (formulář modelu BornDigitalArticle) a Poznázvu (formulář modelu  SimpleCejshArticle)
> issue #610: fix subtitle control

- proarc-webapp/src/main/java/cz/cas/lib/proarc/webapp/client/ds/MetaModelDataSource.java
- proarc-webapp/src/main/java/cz/cas/lib/proarc/webapp/client/widget/DigitalObjectChildrenEditor.java
- proarc-webapp/src/main/resources/cz/cas/lib/proarc/webapp/client/ClientMessages.properties
- proarc-webapp/src/main/resources/cz/cas/lib/proarc/webapp/client/ClientMessages_cs.properties
In relations editor, "New" menu:
extended submenu for each item with "add with params"
> issue #584: create object with uuid from relations

- proarc-common/src/main/java/cz/cas/lib/proarc/common/object/emods/BdmArticleMapper.java
- proarc-common/src/test/java/cz/cas/lib/proarc/common/object/emods/BdmArticleMapperTest.java
- proarc-webapp/src/main/java/cz/cas/lib/proarc/webapp/client/widget/mods/bdm/BornDigitalArticleForm.java
- proarc-webapp/src/main/java/cz/cas/lib/proarc/webapp/client/widget/mods/bdm/SimpleCejshArticleForm.java
Ve zjednodušeném formuláři možnost zaznamenat do elementu PhysicalDescriotion/form jednu ze 3 možností. Na základě této hodnoty se vytvoří při uložení nové PhysicalDescription. Hodnoty vychází z tabulky u #609.
> issue #609: BornDigitalArticle add rdamedia and rdacarrier

- proarc-common/src/main/java/cz/cas/lib/proarc/common/object/oldprint/OldPrintPlugin.java
+ changed metamodel ordering -> Old Print Multipart Monograph is now
above Old Print Volume
> issue #627: Moved OPMM above OPV

- proarc-webapp/src/main/java/cz/cas/lib/proarc/webapp/client/widget/mods/NdkArticleForm.java
- proarc-webapp/src/main/java/cz/cas/lib/proarc/webapp/client/widget/mods/NdkCartographicForm.java
- proarc-webapp/src/main/java/cz/cas/lib/proarc/webapp/client/widget/mods/NdkChapterForm.java
- proarc-webapp/src/main/java/cz/cas/lib/proarc/webapp/client/widget/mods/NdkMonographSupplementForm.java
- proarc-webapp/src/main/java/cz/cas/lib/proarc/webapp/client/widget/mods/NdkMonographTitleForm.java
- proarc-webapp/src/main/java/cz/cas/lib/proarc/webapp/client/widget/mods/NdkMonographVolumeForm.java
- proarc-webapp/src/main/java/cz/cas/lib/proarc/webapp/client/widget/mods/NdkPeriodicalForm.java
- proarc-webapp/src/main/java/cz/cas/lib/proarc/webapp/client/widget/mods/NdkPeriodicalIssueForm.java
- proarc-webapp/src/main/java/cz/cas/lib/proarc/webapp/client/widget/mods/NdkPeriodicalSupplementForm.java
- proarc-webapp/src/main/java/cz/cas/lib/proarc/webapp/client/widget/mods/NdkPeriodicalVolumeForm.java
- proarc-webapp/src/main/java/cz/cas/lib/proarc/webapp/client/widget/mods/NdkPictureForm.java
- proarc-webapp/src/main/java/cz/cas/lib/proarc/webapp/client/widget/mods/NdkSheetMusicForm.java
- proarc-webapp/src/main/java/cz/cas/lib/proarc/webapp/client/widget/mods/bdm/BornDigitalArticleForm.java
Opraveny povinnosti u elementů
> issue #612: forms - repair element description

- proarc-common/src/main/java/cz/cas/lib/proarc/common/dublincore/DcStreamEditor.java
- proarc-common/src/main/java/cz/cas/lib/proarc/common/fedora/WorkflowStorage.java
- proarc-common/src/main/java/cz/cas/lib/proarc/common/fedora/relation/RelationEditor.java
- proarc-common/src/main/java/cz/cas/lib/proarc/common/mods/ndk/NdkMapper.java
- proarc-common/src/main/java/cz/cas/lib/proarc/common/object/DesDesaPlugin.java
- proarc-common/src/main/java/cz/cas/lib/proarc/common/object/DescriptionMetadata.java
- proarc-common/src/main/java/cz/cas/lib/proarc/common/object/DigitalObjectHandler.java
- proarc-common/src/main/java/cz/cas/lib/proarc/common/object/DigitalObjectManager.java
- proarc-common/src/main/java/cz/cas/lib/proarc/common/object/K4Plugin.java
- proarc-common/src/main/java/cz/cas/lib/proarc/common/object/ndk/NdkMetadataHandler.java
- proarc-common/src/main/java/cz/cas/lib/proarc/common/workflow/PhysicalMaterialBuilder.java
- proarc-common/src/main/java/cz/cas/lib/proarc/common/workflow/WorkflowManager.java
- proarc-webapp/src/main/java/cz/cas/lib/proarc/webapp/client/Editor.java
- proarc-webapp/src/main/java/cz/cas/lib/proarc/webapp/client/ds/DigitalObjectDataSource.java
- proarc-webapp/src/main/java/cz/cas/lib/proarc/webapp/client/ds/RestConfig.java
- proarc-webapp/src/main/java/cz/cas/lib/proarc/webapp/client/ds/WorkflowModsCustomDataSource.java
- proarc-webapp/src/main/java/cz/cas/lib/proarc/webapp/client/presenter/ModsCustomEditor.java
- proarc-webapp/src/main/java/cz/cas/lib/proarc/webapp/client/presenter/ModsXmlEditor.java
- proarc-webapp/src/main/java/cz/cas/lib/proarc/webapp/client/presenter/WorkflowManaging.java
- proarc-webapp/src/main/java/cz/cas/lib/proarc/webapp/client/presenter/WorkflowNewJob.java
- proarc-webapp/src/main/java/cz/cas/lib/proarc/webapp/client/presenter/WorkflowNewJobEditor.java
- proarc-webapp/src/main/java/cz/cas/lib/proarc/webapp/client/widget/workflow/WorkflowNewJobView.java
- proarc-webapp/src/main/java/cz/cas/lib/proarc/webapp/server/rest/WorkflowResource.java
- proarc-webapp/src/main/java/cz/cas/lib/proarc/webapp/shared/rest/WorkflowResourceApi.java
- proarc-webapp/src/main/resources/cz/cas/lib/proarc/webapp/client/ClientMessages.properties
- proarc-webapp/src/main/resources/cz/cas/lib/proarc/webapp/client/ClientMessages_cs.properties
Je možné založit prázdný záměr a v následujícím kroku ho vyplnit ručně (pro každý formulář je jiný model).
> Issue 602: edit form for workflow job

- proarc-common/src/main/java/cz/cas/lib/proarc/common/catalog/DigitizationRegistryCatalog.java
- proarc-common/src/main/java/cz/cas/lib/proarc/common/catalog/MetadataItem.java
- proarc-common/src/main/java/cz/cas/lib/proarc/common/workflow/PhysicalMaterialBuilder.java
- proarc-common/src/main/java/cz/cas/lib/proarc/common/workflow/WorkflowManager.java
- proarc-common/src/main/java/cz/cas/lib/proarc/common/workflow/model/MaterialView.java
- proarc-common/src/main/java/cz/cas/lib/proarc/common/workflow/model/PhysicalMaterial.java
- proarc-common/src/test/java/cz/cas/lib/proarc/common/dao/empiredb/EmpireWorkflowMaterialDaoTest.java
- proarc-common/src/test/java/cz/cas/lib/proarc/common/workflow/WorkflowManagerTest.java
- proarc-webapp/src/main/java/cz/cas/lib/proarc/webapp/client/ds/BibliographyQueryDataSource.java
- proarc-webapp/src/main/java/cz/cas/lib/proarc/webapp/client/widget/CatalogBrowser.java
- proarc-webapp/src/main/java/cz/cas/lib/proarc/webapp/client/widget/workflow/WorkflowNewJobView.java
- proarc-webapp/src/main/java/cz/cas/lib/proarc/webapp/server/rest/WorkflowResource.java
- proarc-webapp/src/main/java/cz/cas/lib/proarc/webapp/shared/rest/WorkflowResourceApi.java
Při stažení záznamu se do DB uloží identifikátory Pole 001, Sigla, Signatura a v případě registru i rdcz_id. Bylo to nutné, aby správně fungovala automatizace v RDFlow.
Hodnoty z DB se načítají do formuláře, tak to vyřeší i issue #504.
>  Issue #504: ukládání identifikátorů v RDFlow

- proarc-common/src/main/java/cz/cas/lib/proarc/common/workflow/WorkflowActionHandler.java
- proarc-common/src/main/java/cz/cas/lib/proarc/common/workflow/profile/ActionDefinition.java
- proarc-common/src/main/java/cz/cas/lib/proarc/common/workflow/profile/TaskDefinition.java
- proarc-common/src/main/java/cz/cas/lib/proarc/common/workflow/profile/WorkflowProfileConsts.java
- proarc-common/src/main/resources/cz/cas/lib/proarc/common/workflow/profile/workflow.xsd
- proarc-webapp/src/main/java/cz/cas/lib/proarc/webapp/server/rest/WorkflowResource.java
Ve workflow.xml je mozne dodefinovat skript, ktery bude automaticky spusten po uzavreni ukolu.
Parametrem je mozne pridat hodnoty z workflow (path, pid, barcode, source, field001, metadata, sigla, signature, rcdczId).
```
<task name = "task.chooseTitle">
<title lang="cs">Výběr titulu</title>
<hint lang="cs">Výběr titulu k digitalizaci. </hint>
<hint lang="en">Choice of Title</hint>
<setMaterial materialRef="material.physicalObject" way="INPUT" />
<action command="/tmp/script.sh">
<arg>sigla</arg>
</action>
</task>
```
> Issue #643: workflow action runner

- proarc-webapp/src/main/java/cz/cas/lib/proarc/webapp/client/presenter/ModsCustomEditor.java
- proarc-webapp/src/main/java/cz/cas/lib/proarc/webapp/client/widget/mods/PageForm.java
+ prevents glitching gwt
+ does not glitch editor change
> issue #645: set normalpage note to fixed, large enough size

- .travis.yml
- proarc-common/pom.xml
- proarc-common/src/test/java/cz/cas/lib/proarc/common/dao/empiredb/EmpireWorkflowMaterialDaoTest.java
Travis doplneny o sluzbu Postgres + drobna oprava v testech.
> issue #527: travis, postgres

- .travis.yml
- pom.xml
- proarc-webapp/src/main/java/cz/cas/lib/proarc/webapp/client/presenter/ModsCustomEditor.java
- proarc-webapp/src/main/java/cz/cas/lib/proarc/webapp/client/widget/mods/PageForm.java
Smazal jsem ten problematický workaround a aktualizoval smartgwt, ve kterém je už chyba radiobuttonu fixnutá.
Není to úplně nejnovější verze, v té (2017-11-16 i 2017-11-14) je bug, kvůli kterému se nedá uložit formulář.
> issue #645: Smazání problematického workaroundu

- proarc-webapp/src/main/java/cz/cas/lib/proarc/webapp/client/presenter/ModsCustomEditor.java
zapomenuty radek (prestaly se ukladat formulare)
> issue #645: restore deleted line

- .travis.yml
- pom.xml
nastavená cache pro Travis
aktualizováno smartgwt
> issue #527: cache added, smartgwt updated (old version is removed)

- proarc-common/src/main/java/cz/cas/lib/proarc/common/export/mets/Const.java
- proarc-common/src/main/java/cz/cas/lib/proarc/common/export/mets/structure/MetsElementVisitor.java
- proarc-common/src/test/java/cz/cas/lib/proarc/common/export/mets/MetsUtilsTest.java
- proarc-common/src/test/java/cz/cas/lib/proarc/common/export/mets/NdkExportTest.java
Odstranění velkých písmen v názvech souborů.
> issue #169: filename lowercase

- proarc-common/src/main/java/cz/cas/lib/proarc/common/export/mets/MetsUtils.java
- proarc-common/src/test/java/cz/cas/lib/proarc/common/export/mets/MetsUtilsTest.java
Do itemListu v souboru info.xml byl přidán odkaz na tento info.xml file. Zvětšil se rovněž počet souborů a jeden soubor a oprava testu.
> issue #668: add info.xml to item list

- pom.xml
- proarc-auth/pom.xml
- proarc-common/pom.xml
- proarc-desa/pom.xml
- proarc-mets/pom.xml
- proarc-mix/pom.xml
- proarc-mods/pom.xml
- proarc-nsesss/pom.xml
- proarc-oaidublincore/pom.xml
- proarc-premis/pom.xml
- proarc-urnnbn/pom.xml
- proarc-webapp/pom.xml
- proarc-z3950/pom.xml
> #issue701: Release version 3.4

- proarc-webapp/src/main/java/cz/cas/lib/proarc/webapp/client/widget/mods/NdkCartographicForm.java
- proarc-webapp/src/main/java/cz/cas/lib/proarc/webapp/client/widget/mods/NdkMonographVolumeForm.java
- proarc-webapp/src/main/java/cz/cas/lib/proarc/webapp/client/widget/mods/NdkPeriodicalForm.java
- proarc-webapp/src/main/java/cz/cas/lib/proarc/webapp/client/widget/mods/NdkSheetMusicForm.java
- proarc-webapp/src/main/java/cz/cas/lib/proarc/webapp/client/widget/mods/oldprint/OldPrintVolumeForm.java
Oprava OriginInfo Issuance - podle MODsu nemá být mezi slovy podržítko ale klasická mezera.
> issue #705: fix OriginInfo Issuance

- proarc-common/src/main/java/cz/cas/lib/proarc/common/mods/ndk/NdkMonographTitleMapper.java
- proarc-webapp/src/main/java/cz/cas/lib/proarc/webapp/client/widget/mods/NdkMonographTitleForm.java
Do formuláře NDK Vícesvazkové monografie přidán element Language, který se následně přebírá i do Dublin Coru.
> issue #651: add element Language to NdkMonographTitle

- proarc-webapp/src/main/java/cz/cas/lib/proarc/webapp/client/widget/mods/NdkCartographicForm.java
- proarc-webapp/src/main/java/cz/cas/lib/proarc/webapp/client/widget/mods/NdkMonographSupplementForm.java
- proarc-webapp/src/main/java/cz/cas/lib/proarc/webapp/client/widget/mods/NdkMonographTitleForm.java
- proarc-webapp/src/main/java/cz/cas/lib/proarc/webapp/client/widget/mods/NdkMonographVolumeForm.java
- proarc-webapp/src/main/java/cz/cas/lib/proarc/webapp/client/widget/mods/NdkMusicDocumentForm.java
- proarc-webapp/src/main/java/cz/cas/lib/proarc/webapp/client/widget/mods/NdkPeriodicalForm.java
- proarc-webapp/src/main/java/cz/cas/lib/proarc/webapp/client/widget/mods/NdkPeriodicalIssueForm.java
- proarc-webapp/src/main/java/cz/cas/lib/proarc/webapp/client/widget/mods/NdkPeriodicalSupplementForm.java
- proarc-webapp/src/main/java/cz/cas/lib/proarc/webapp/client/widget/mods/NdkPeriodicalVolumeForm.java
- proarc-webapp/src/main/java/cz/cas/lib/proarc/webapp/client/widget/mods/NdkPictureForm.java
- proarc-webapp/src/main/java/cz/cas/lib/proarc/webapp/client/widget/mods/NdkSheetMusicForm.java
- proarc-webapp/src/main/java/cz/cas/lib/proarc/webapp/client/widget/mods/NdkTrackForm.java
- proarc-webapp/src/main/java/cz/cas/lib/proarc/webapp/client/widget/mods/oldprint/OldPrintSupplementForm.java
- proarc-webapp/src/main/java/cz/cas/lib/proarc/webapp/client/widget/mods/oldprint/OldPrintVolumeForm.java
Tato úprava zahrnuje změny v nápovědních bublinář u formulářů.
Tento PR se týká těchto issue:
- #700 
- #170 
- #171 
- #173 
- #175 
-  #180 
- #196 
- #198
> issue #700: Hints

- proarc-webapp/src/main/java/cz/cas/lib/proarc/webapp/client/widget/form/FormGenerator.java
- proarc-webapp/src/main/java/cz/cas/lib/proarc/webapp/client/widget/form/MAMFieldValidator.java
- proarc-webapp/src/main/java/cz/cas/lib/proarc/webapp/client/widget/mods/RepeatableForm.java
- MA and M type Field is now decided based on title string, this should
be based on required(enum) probably
> issue #703: Added conditional validation for MA subforms

- .travis.yml
- proarc-common/src/test/java/cz/cas/lib/proarc/common/dao/empiredb/EmpireBatchDaoTest.java
- proarc-common/src/test/resources/cz/cas/lib/proarc/common/dao/empiredb/batch.xml
- proarc-common/src/test/resources/cz/cas/lib/proarc/common/dao/empiredb/batch_single_item.xml
- proarc-common/src/test/resources/cz/cas/lib/proarc/common/dao/empiredb/batch_with_items.xml
- proarc-common/src/test/resources/cz/cas/lib/proarc/common/dao/empiredb/group.xml
- proarc-common/src/test/resources/cz/cas/lib/proarc/common/dao/empiredb/user.xml
- fixed mismatched expected count numbers
- added missing user element in test XML files
- fixed EmpireGroupDaoTest failing if run after workflow tests
> issue #527: Fixed failing DB tests

- proarc-webapp/src/main/java/cz/cas/lib/proarc/webapp/client/action/export/ArchiveExportAction.java
- proarc-webapp/src/main/java/cz/cas/lib/proarc/webapp/client/action/export/CejshExportAction.java
- proarc-webapp/src/main/java/cz/cas/lib/proarc/webapp/client/action/export/CrossrefExportAction.java
- proarc-webapp/src/main/java/cz/cas/lib/proarc/webapp/client/action/export/DataStreamExportAction.java
- proarc-webapp/src/main/java/cz/cas/lib/proarc/webapp/client/action/export/DesaExportAction.java
- proarc-webapp/src/main/java/cz/cas/lib/proarc/webapp/client/action/export/ExportAction.java
- proarc-webapp/src/main/java/cz/cas/lib/proarc/webapp/client/action/export/KrameriusExportAction.java
- proarc-webapp/src/main/java/cz/cas/lib/proarc/webapp/client/action/export/NdkExportAction.java
- proarc-webapp/src/main/resources/cz/cas/lib/proarc/webapp/client/ClientMessages.properties
- proarc-webapp/src/main/resources/cz/cas/lib/proarc/webapp/client/ClientMessages_cs.properties
- triggering export action from UI now does not block user with prompt
- export action done messages now contain name of the action
> issue #711: Non blocking export actions

- proarc-webapp/src/main/java/cz/cas/lib/proarc/webapp/client/widget/form/FormGenerator.java
- proarc-webapp/src/main/java/cz/cas/lib/proarc/webapp/client/widget/form/MAMFieldValidator.java
- true corresponds to RDA and false to AACR in fieldsToIgnore
- values in fieldsToIgnore represent fields with special rules when to
ignore their requirement (what to ignore, when to ignore)
> issue #727: Event Type not mandatory if RDA rules is AACR

- proarc-webapp/src/main/java/cz/cas/lib/proarc/webapp/client/widget/mods/NdkMonographVolumeForm.java
- proarc-webapp/src/main/java/cz/cas/lib/proarc/webapp/client/widget/mods/NdkPeriodicalForm.java
- proarc-webapp/src/main/java/cz/cas/lib/proarc/webapp/client/widget/mods/oldprint/OldPrintVolumeForm.java
Odebrány nadbytečné možnosti u titulu periodika v elementu Issuance
> issue #724: remove extra possibilities from OriginInfo:Issuance

- proarc-common/src/main/java/cz/cas/lib/proarc/common/config/AppConfiguration.java
- proarc-common/src/main/java/cz/cas/lib/proarc/common/object/ndk/NdkMetadataHandler.java
- proarc-common/src/main/java/cz/cas/lib/proarc/common/object/ndk/RdaRules.java
- proarc-common/src/main/resources/cz/cas/lib/proarc/common/config/proarc.properties
Preferovaná hodnota přepínače RDA / AACR je nyní možné nastavit v konfiguračním souboru. Pokud není v konfiguračním souboru tato hodnota nastavena, nebo je použita jiná hodnota než *AACR*, použije se hodnota *RDA*.
> issue #722: default value in descriptionStandard is configurated

- proarc-common/pom.xml
- proarc-common/src/test/java/cz/cas/lib/proarc/common/jobs/BatchImportJobTest.java
- updated quartz version
- changed test scheduler to non-static
- ignored malfunctioning test due to a bug in Quartz library
> Quartz test fix + version update

- proarc-common/src/main/java/cz/cas/lib/proarc/common/export/Kramerius4Export.java
- proarc-common/src/main/java/cz/cas/lib/proarc/common/export/Kramerius4ExportOptions.java
- proarc-common/src/main/java/cz/cas/lib/proarc/common/object/K4Plugin.java
Jesliže svazek monografie spadá pod vícesvazkovou monografii, opraví se dc:type na model:monographunit. Jinak zůstává model:monograph
> issue #738: fix K4 export

- proarc-webapp/src/main/java/cz/cas/lib/proarc/webapp/client/widget/mods/NdkForms.java
- proarc-webapp/src/main/java/cz/cas/lib/proarc/webapp/client/widget/mods/eborn/NdkEmonographVolumeForm.java
Zobrazují se i ostatní formuláře kromě NDK. 
Problémem byl NPE na frontendu.
> issue #781: fix forms

- proarc-common/src/main/java/cz/cas/lib/proarc/common/dublincore/DcUtils.java
- proarc-common/src/main/java/cz/cas/lib/proarc/common/export/mets/Const.java
- proarc-common/src/main/java/cz/cas/lib/proarc/common/export/mets/structure/MetsElement.java
- proarc-common/src/main/java/cz/cas/lib/proarc/common/export/mets/structure/MetsElementVisitor.java
- proarc-common/src/main/java/cz/cas/lib/proarc/common/i18n/BundleName.java
- proarc-common/src/main/java/cz/cas/lib/proarc/common/mods/custom/ModsConstants.java
- proarc-common/src/main/java/cz/cas/lib/proarc/common/mods/ndk/NdkMapper.java
- proarc-common/src/main/java/cz/cas/lib/proarc/common/mods/ndk/NdkMapperFactory.java
- proarc-common/src/main/java/cz/cas/lib/proarc/common/mods/ndk/NdkPageMapper.java
- proarc-common/src/main/java/cz/cas/lib/proarc/common/object/ndk/NdkMetadataHandler.java
- proarc-common/src/main/java/cz/cas/lib/proarc/common/object/ndk/NdkPlugin.java
- proarc-common/src/main/java/cz/cas/lib/proarc/common/object/oldprint/OldPrintPageMapper.java
- proarc-common/src/main/java/cz/cas/lib/proarc/common/object/oldprint/OldPrintPlugin.java
- proarc-common/src/main/resources/cz/cas/lib/proarc/common/config/modsPageTypes.properties
- proarc-common/src/main/resources/cz/cas/lib/proarc/common/config/modsPageTypes_cs.properties
- proarc-common/src/main/resources/metamodel/model_ndkpage.xml
- proarc-common/src/test/java/cz/cas/lib/proarc/common/mods/ndk/NdkPageMapperTest.java
- proarc-common/src/test/java/cz/cas/lib/proarc/common/object/oldprint/OldPrintPageMapperTest.java
- proarc-webapp/src/main/java/cz/cas/lib/proarc/webapp/client/presenter/ModsBatchEditor.java
- proarc-webapp/src/main/java/cz/cas/lib/proarc/webapp/client/widget/mods/NdkForms.java
- proarc-webapp/src/main/java/cz/cas/lib/proarc/webapp/client/widget/mods/NdkPageForm.java
- proarc-webapp/src/main/java/cz/cas/lib/proarc/webapp/client/widget/mods/oldprint/OldPrintForms.java
- proarc-webapp/src/main/resources/cz/cas/lib/proarc/webapp/ProArc.gwt.xml
- proarc-webapp/src/main/webapp/META-INF/context.xml
Vytvořen nový model ndkPage vrámci pluginu NDK
> issue #814: Nový model NdkPage

- proarc-common/src/main/java/cz/cas/lib/proarc/common/object/ndk/RdaRules.java
- proarc-webapp/src/main/resources/cz/cas/lib/proarc/webapp/server/ServerMessages.properties
- proarc-webapp/src/main/resources/cz/cas/lib/proarc/webapp/server/ServerMessages_cs.properties
Add exception if eventType is null when descriptionStanda…rd is RDA
> issue #828: RDA rules add exception

- proarc-common/src/main/java/cz/cas/lib/proarc/common/mods/ndk/MapperUtils.java
Edebírá mezeru z pole, jestliže je type=null
> issue #689: remove space from dc:creator

- proarc-common/src/main/resources/xml/MARC21slim2MODS3.xsl
- proarc-common/src/test/resources/cz/cas/lib/proarc/common/xml/alephXServerDetailResponseAsMods.xml
> issue #689: author name

- proarc-common/src/main/java/cz/cas/lib/proarc/common/export/mets/Const.java
- proarc-common/src/main/java/cz/cas/lib/proarc/common/export/mets/MetsUtils.java
- proarc-common/src/main/java/cz/cas/lib/proarc/common/export/mets/NdkExport.java
- proarc-common/src/main/java/cz/cas/lib/proarc/common/export/mets/NdkSttExport.java
- proarc-common/src/main/java/cz/cas/lib/proarc/common/export/mets/structure/MetsElementVisitor.java
- proarc-common/src/main/java/cz/cas/lib/proarc/common/export/mets/structure/SttElementVisitor.java
- proarc-common/src/main/java/cz/cas/lib/proarc/common/mods/ndk/NdkMapper.java
- proarc-common/src/main/java/cz/cas/lib/proarc/common/object/oldprint/OldPrintMapperFactory.java
- proarc-common/src/main/java/cz/cas/lib/proarc/common/object/oldprint/OldPrintPlugin.java
- proarc-webapp/src/main/java/cz/cas/lib/proarc/webapp/client/action/export/NdkExportAction.java
- proarc-webapp/src/main/java/cz/cas/lib/proarc/webapp/client/action/export/NdkOldPrintExportAction.java
- proarc-webapp/src/main/java/cz/cas/lib/proarc/webapp/client/presenter/DigitalObjectManager.java
- proarc-webapp/src/main/java/cz/cas/lib/proarc/webapp/server/rest/ExportResource.java
- proarc-webapp/src/main/java/cz/cas/lib/proarc/webapp/shared/rest/ExportResourceApi.java
- proarc-webapp/src/main/resources/cz/cas/lib/proarc/webapp/client/ClientMessages.properties
- proarc-webapp/src/main/resources/cz/cas/lib/proarc/webapp/client/ClientMessages_cs.properties
Implementace NDK exportu pro STT modely. 
ALTO a OCR nejsou u tohoto balíčku nutné.
> issue #624: client implementation [do not merge]

- proarc-common/src/main/java/cz/cas/lib/proarc/common/object/ndk/NdkMetadataHandler.java
> Revert "issue #977: Dont copy identifiers"
