proarc/proarc

- proarc-common/src/main/java/cz/cas/lib/proarc/common/i18n/BundleValueMap.java
- proarc-common/src/main/java/cz/cas/lib/proarc/common/mods/ndk/NdkPageMapper.java
- proarc-common/src/main/java/cz/cas/lib/proarc/common/object/ndk/NdkPlugin.java
- proarc-common/src/main/java/cz/cas/lib/proarc/common/object/oldprint/OldPrintPageMapper.java
- proarc-common/src/test/java/cz/cas/lib/proarc/common/object/oldprint/OldPrintPageMapperTest.java
- proarc-webapp/src/main/java/cz/cas/lib/proarc/webapp/server/ServerMessages.java
- proarc-webapp/src/main/java/cz/cas/lib/proarc/webapp/server/rest/LocalizationResource.java
File missing suffix "_en" was not detected as english resource bundle
without default Locale set to Locale.ENGLISH.
> issue #541: set default locale to English in test

- proarc-webapp/src/main/java/cz/cas/lib/proarc/webapp/client/widget/CanvasSizePersistence.java
- proarc-webapp/src/main/java/cz/cas/lib/proarc/webapp/client/widget/workflow/WorkflowJobFormView.java
- proarc-webapp/src/main/java/cz/cas/lib/proarc/webapp/client/widget/workflow/WorkflowJobView.java
- proarc-webapp/src/main/java/cz/cas/lib/proarc/webapp/client/widget/workflow/WorkflowMaterialView.java
- proarc-webapp/src/main/java/cz/cas/lib/proarc/webapp/client/widget/workflow/WorkflowTaskFormView.java
Gettry ve třídě CanvasSizePersistence působí trochu divně, ale má to svůj důvod. Třída Offline se chová trochu neočekávatelně, i když vložím do hodnoty Integer (podle javadocu můžu bere Object), tak při získávání explicitní přetypování na Integer vyhodí `Classcastexception`.
Trochu to řeší i issue https://github.com/proarc/proarc/issues/386 - uživatel si může roztáhnout pole s formulářem a naroste mu i poznámka. 
Nevím v čem u poznámky spočíval bug ve Smartgwt 4. Ve SmartGWT 6 se to taky nechová nejlépe - spolu s poznámkou narůstá minimální výška formuláře na úkor ostatních oddílů (v případě opravdu dlouhé pozánky se k nim poté nedostanu).
> issue #533: Možnost měnit velikost oddílů v RDflow

- proarc-common/src/test/java/cz/cas/lib/proarc/common/export/mets/MetsUtilsTest.java
Po úpravě je METS soubor o 126 bytů větší, balíček těsně překonal hranici 21 kB - přestaly procházet testy.
Projeví se to jenom na Linuxu, ve Windows test prochází jinou větví (https://github.com/proarc/proarc/blob/f95f5a230cbb40fb1dbe83e65a3ddce029a0eb87/proarc-common/src/test/java/cz/cas/lib/proarc/common/export/mets/MetsUtilsTest.java#L206-L208).
Opraveno.
> issue #515: Po úpravě neprochází testy na Linuxu

- proarc-webapp/src/main/java/cz/cas/lib/proarc/webapp/client/widget/mods/NdkCartographicForm.java
- proarc-webapp/src/main/java/cz/cas/lib/proarc/webapp/client/widget/mods/NdkChapterForm.java
- proarc-webapp/src/main/java/cz/cas/lib/proarc/webapp/client/widget/mods/NdkMonographSupplementForm.java
- proarc-webapp/src/main/java/cz/cas/lib/proarc/webapp/client/widget/mods/NdkMonographVolumeForm.java
- proarc-webapp/src/main/java/cz/cas/lib/proarc/webapp/client/widget/mods/NdkPeriodicalForm.java
- proarc-webapp/src/main/java/cz/cas/lib/proarc/webapp/client/widget/mods/NdkPeriodicalSupplementForm.java
- proarc-webapp/src/main/java/cz/cas/lib/proarc/webapp/client/widget/mods/NdkPictureForm.java
- proarc-webapp/src/main/java/cz/cas/lib/proarc/webapp/client/widget/mods/NdkSheetMusicForm.java
Podle #587 přidána možná hodnota “gmd” u atributu authority elementu <mods:form> v sekci Physical Description
Ve specifikaci https://docs.google.com/document/d/1cWvwfk9bVpTGfeSwQOKfDQlbIyEkJEL-LcMU6bmQL1A/edit#heading=h.30j0zll bod 1.
> issue #587: Add authority gmd to element <mods:form>

- proarc-common/src/main/java/cz/cas/lib/proarc/common/export/mets/Const.java
- proarc-common/src/main/java/cz/cas/lib/proarc/common/export/mets/MetsUtils.java
- proarc-common/src/main/java/cz/cas/lib/proarc/common/export/mets/structure/MetsElementVisitor.java
- proarc-common/src/test/java/cz/cas/lib/proarc/common/export/mets/MetsUtilsTest.java
- proarc-common/src/test/java/cz/cas/lib/proarc/common/export/mets/NdkExportTest.java
Podle #517  přidány události, které se zapisují do amdSec při exportu.
Vychází ze standardu http://www.ndk.cz/standardy-digitalizace/DMFperiodika_16.pdf na straně 61.
> issue #517: add eventType to Premis

- proarc-common/src/main/java/cz/cas/lib/proarc/common/mods/ndk/NdkArticleMapper.java
- proarc-common/src/main/java/cz/cas/lib/proarc/common/mods/ndk/NdkCartographicMapper.java
- proarc-common/src/main/java/cz/cas/lib/proarc/common/mods/ndk/NdkChapterMapper.java
- proarc-common/src/main/java/cz/cas/lib/proarc/common/mods/ndk/NdkMapper.java
- proarc-common/src/main/java/cz/cas/lib/proarc/common/mods/ndk/NdkMonographSupplementMapper.java
- proarc-common/src/main/java/cz/cas/lib/proarc/common/mods/ndk/NdkMonographVolumeMapper.java
- proarc-common/src/main/java/cz/cas/lib/proarc/common/mods/ndk/NdkPeriodicalMapper.java
- proarc-common/src/main/java/cz/cas/lib/proarc/common/mods/ndk/NdkPeriodicalSupplementMapper.java
- proarc-common/src/main/java/cz/cas/lib/proarc/common/mods/ndk/NdkPictureMapper.java
- proarc-common/src/main/java/cz/cas/lib/proarc/common/mods/ndk/NdkSheetMusicMapper.java
- proarc-webapp/src/main/java/cz/cas/lib/proarc/webapp/client/widget/mods/NdkArticleForm.java
- proarc-webapp/src/main/java/cz/cas/lib/proarc/webapp/client/widget/mods/NdkCartographicForm.java
- proarc-webapp/src/main/java/cz/cas/lib/proarc/webapp/client/widget/mods/NdkChapterForm.java
- proarc-webapp/src/main/java/cz/cas/lib/proarc/webapp/client/widget/mods/NdkMonographSupplementForm.java
- proarc-webapp/src/main/java/cz/cas/lib/proarc/webapp/client/widget/mods/NdkMonographVolumeForm.java
- proarc-webapp/src/main/java/cz/cas/lib/proarc/webapp/client/widget/mods/NdkPeriodicalForm.java
- proarc-webapp/src/main/java/cz/cas/lib/proarc/webapp/client/widget/mods/NdkPeriodicalSupplementForm.java
- proarc-webapp/src/main/java/cz/cas/lib/proarc/webapp/client/widget/mods/NdkPictureForm.java
- proarc-webapp/src/main/java/cz/cas/lib/proarc/webapp/client/widget/mods/NdkSheetMusicForm.java
- proarc-webapp/src/main/java/cz/cas/lib/proarc/webapp/client/widget/mods/bdm/BornDigitalArticleForm.java
Podle #592  upraven formulář metadat tak, aby bylo možné zaznamenat do <mods:classification> klasifikační údaje věcného třídění podle Konspektu. 
Současná verze šablony již umí stáhnout tyto pole a údaje se přenesou přímo do formuláře (Vyplní se, jak hodnota Authority, tak i hodnota edition). Zkoušeno na monografii stažené z Alephu ISBN = 978-80-7390-006-9.
Ve specifikaci bod https://docs.google.com/document/d/1cWvwfk9bVpTGfeSwQOKfDQlbIyEkJEL-LcMU6bmQL1A/edit#heading=h.1t3h5sf
> issue #592: Add value "Konspekt" to element <mods:classification>

- proarc-webapp/src/main/java/cz/cas/lib/proarc/webapp/client/widget/mods/NdkArticleForm.java
- proarc-webapp/src/main/java/cz/cas/lib/proarc/webapp/client/widget/mods/NdkCartographicForm.java
- proarc-webapp/src/main/java/cz/cas/lib/proarc/webapp/client/widget/mods/NdkChapterForm.java
- proarc-webapp/src/main/java/cz/cas/lib/proarc/webapp/client/widget/mods/NdkMonographSupplementForm.java
- proarc-webapp/src/main/java/cz/cas/lib/proarc/webapp/client/widget/mods/NdkMonographVolumeForm.java
- proarc-webapp/src/main/java/cz/cas/lib/proarc/webapp/client/widget/mods/NdkPeriodicalForm.java
- proarc-webapp/src/main/java/cz/cas/lib/proarc/webapp/client/widget/mods/NdkPeriodicalIssueForm.java
- proarc-webapp/src/main/java/cz/cas/lib/proarc/webapp/client/widget/mods/NdkPeriodicalSupplementForm.java
- proarc-webapp/src/main/java/cz/cas/lib/proarc/webapp/client/widget/mods/NdkPictureForm.java
- proarc-webapp/src/main/java/cz/cas/lib/proarc/webapp/client/widget/mods/NdkSheetMusicForm.java
- proarc-webapp/src/main/java/cz/cas/lib/proarc/webapp/client/widget/mods/bdm/BornDigitalArticleForm.java
Podle #594 upraven formulář metadat tak, aby bylo možné zaznamenat do mods:subject klasifikační údaje věcného třídění podle Konspektu.
Současná verze šablony již umí stáhnout tyto pole a údaje se přenesou přímo do formuláře (Vyplní se, jak hodnota Authority, tak i hodnota topic). Zkoušeno na monografii stažené z Alephu ISBN = 978-80-7390-006-9.
Ve specifikaci bod https://docs.google.com/document/d/1cWvwfk9bVpTGfeSwQOKfDQlbIyEkJEL-LcMU6bmQL1A/edit#heading=h.4d34og8
> issue #594: Add value "Konspekt" to element <mods:subject>

- proarc-common/src/main/java/cz/cas/lib/proarc/common/mods/ndk/NdkPeriodicalMapper.java
- proarc-common/src/main/java/cz/cas/lib/proarc/common/mods/ndk/NdkPeriodicalVolumeMapper.java
- proarc-common/src/test/java/cz/cas/lib/proarc/common/mods/ndk/NdkPeriodicalMapperTest.java
- proarc-common/src/test/java/cz/cas/lib/proarc/common/mods/ndk/NdkPeriodicalVolumeMapperTest.java
- proarc-webapp/src/main/java/cz/cas/lib/proarc/webapp/client/widget/mods/NdkPeriodicalForm.java
- proarc-webapp/src/main/java/cz/cas/lib/proarc/webapp/client/widget/mods/NdkPeriodicalVolumeForm.java
Podle #588  upraven formulář titulu periodika a ročníku tak, aby se dalo zaznamenat mods:name, mods:namePart, mods:role, mods:roleTerm a dc:creator.
Ve specifikaci https://docs.google.com/document/d/1cWvwfk9bVpTGfeSwQOKfDQlbIyEkJEL-LcMU6bmQL1A/edit#heading=h.3znysh7 bod 3.
> issue #588: Add <name> to Ndk Periodical

- proarc-webapp/src/main/java/cz/cas/lib/proarc/webapp/client/presenter/ModsCustomEditor.java
> Chybu jsme zaznamenali až po nasazení verze 3.3.
Zkoušel jsem Proarc ve verzi 3.2, ale chyba se mi projevila už v něm.
Vypadá to na nějaký bug ve SmartGWT, která se nastane pouze při použití Radio (Select i Combo funguje v pořádku). Zkoušel jsem SmartGWT aktualizovat na aktuální build 6.0p, ale nepomohlo to.
Přikládám změnu obsahující drobný workaround, který problém řeší. Pomůže zavolat clear nad celým widgetem formuláře (https://www.smartclient.com/smartgwt/javadoc/com/smartgwt/client/widgets/Canvas.html#clear--), clearValues je nedostačující.
RadioButton teď funguje, testoval jsem to ve Firefoxu i v Chrome.
Btw. nejspíš z důvodu blbnoucího radia Lukáš použil pro volbu AACR/RDA combo. Radio by bylo v tomto případě vhodnější. Combo je ostatně špatně, uživatel může zadat jakoukoliv …
> issue #557: fix article radiobutton

- proarc-webapp/src/main/java/cz/cas/lib/proarc/webapp/client/ds/StreamProfileDataSource.java
- proarc-webapp/src/main/java/cz/cas/lib/proarc/webapp/client/widget/MediaEditor.java
changed:
+ attribute with request source is now set directly to dsrequest for BDM
uploading
+ template list is returned as unmodifiable list (preventing unexpected
behaviour in future updates)
> issue #427: Set attribute directly to dsRequest

- proarc-webapp/src/main/java/cz/cas/lib/proarc/webapp/client/ds/ModsCustomDataSource.java
- proarc-webapp/src/main/java/cz/cas/lib/proarc/webapp/client/presenter/ModsMultiEditor.java
- proarc-webapp/src/main/java/cz/cas/lib/proarc/webapp/client/presenter/ModsXmlEditor.java
+ failing XML save now promts user whether he wants to ignore validation
issue (thrown when object has sub-objects connected)
+ illegal mods fails even if validation is ignored
+removed unused imports in ModsCustomDataSource
> issue #559: Changed saving XML editor procedure

- proarc-common/src/main/java/cz/cas/lib/proarc/common/export/mets/MetsUtils.java
Podle issue opraveno číslo standardu:
- Periodika z 1.5 na 1.6
- Monografie z 1.1 na 1.2
> issue #628: repair metadata version

- proarc-common/src/main/java/cz/cas/lib/proarc/common/mods/ndk/NdkMapper.java
- proarc-common/src/main/java/cz/cas/lib/proarc/common/mods/ndk/NdkMusicDocumentMapper.java
- proarc-common/src/main/java/cz/cas/lib/proarc/common/mods/ndk/NdkSongMapper.java
- proarc-common/src/main/java/cz/cas/lib/proarc/common/mods/ndk/NdkTrackMapper.java
- proarc-common/src/main/java/cz/cas/lib/proarc/common/object/ndk/NdkAudioPlugin.java
- proarc-common/src/main/java/cz/cas/lib/proarc/common/object/ndk/NdkPlugin.java
- proarc-common/src/main/resources/META-INF/services/cz.cas.lib.proarc.common.object.DigitalObjectPlugin
- proarc-common/src/main/resources/cz/cas/lib/proarc/common/config/proarc.properties
- proarc-common/src/main/resources/metamodel/model_ndkmusicdocument.xml
- proarc-common/src/main/resources/metamodel/model_ndksong.xml
- proarc-common/src/main/resources/metamodel/model_ndktrack.xml
- proarc-webapp/src/main/java/cz/cas/lib/proarc/webapp/client/widget/mods/NdkForms.java
- proarc-webapp/src/main/java/cz/cas/lib/proarc/webapp/client/widget/mods/NdkMusicDocumentForm.java
- proarc-webapp/src/main/java/cz/cas/lib/proarc/webapp/client/widget/mods/NdkSongForm.java
- proarc-webapp/src/main/java/cz/cas/lib/proarc/webapp/client/widget/mods/NdkTrackForm.java
Vytvořen nový plugin podle issue #634.
Plugin se aktivuje přidáním hodnoty ndkAudio do výčtu hodnot v poli: digobject.plugins v souboru proarc.cfg
Modely vychází z již existujících NDK modelů. Mappery k těmto modelů jsou téměř prázdné, neboť nebylo uvedeno, jaké hodnoty se mají vždy doplňovat. Formuláře vychází z dokumentu od Filipa Šíra. Jakmile vyjde nový NDK standard popisující zvukové dokumenty budou upraveny jak formuláře, tak i mappery.
> issue #634: create new NDK Audio Plugin

- proarc-common/src/main/java/cz/cas/lib/proarc/common/fedora/WorkflowStorage.java
Editory vyžadují vždy nějaké XML. Proto se nyní při vytváření prázdného záměru vytvoří prázdný defaultní MODS.
> Workflow - empty job

- proarc-common/src/main/java/cz/cas/lib/proarc/common/export/Kramerius4Export.java
- proarc-common/src/test/java/cz/cas/lib/proarc/common/export/Kramerius4ExportTest.java
- proarc-common/src/test/java/cz/cas/lib/proarc/common/fedora/FedoraTestSupport.java
Prázdné OCR je nahrazeno prázdným řádkem, takový interní datastream už Fedora akceptuje.
> issue #658: workaround for empty OCR (replace it with newline)

- proarc-common/src/main/java/cz/cas/lib/proarc/common/dao/empiredb/EmpireBatchDao.java
- proarc-common/src/main/java/cz/cas/lib/proarc/common/imports/ImportProcess.java
- proarc-common/src/test/java/cz/cas/lib/proarc/common/dao/empiredb/EmpireBatchDaoTest.java
- proarc-common/src/test/resources/cz/cas/lib/proarc/common/dao/empiredb/batch.xml
- proarc-common/src/test/resources/cz/cas/lib/proarc/common/dao/empiredb/batch_with_items.xml
- proarc-webapp/src/main/java/cz/cas/lib/proarc/webapp/server/rest/ImportResource.java
Other users now can edit import batches of user 'proarc' (id 1). Upon ingesting batch into remote storage, username is updated to current user.
> moravianlibrary#2: enable processing import batches of 'proarc' user

- proarc-common/src/main/resources/xml/MARC21slim2MODS3.xsl
- proarc-common/src/main/resources/xml/MARC21slimUtils.xsl
- proarc-common/src/test/java/cz/cas/lib/proarc/common/xml/TransformersTest.java
- Author name is now divided into `family` and `given` part if 100/700
fields contain ','
> issue #689: MARC21 to MODS3 edit: split author name into nameParts

- proarc-common/src/main/java/cz/cas/lib/proarc/common/export/Kramerius4ExportOptions.java
- hasUnit is used since MonographVolume is using it also
- model:monograph is used since MonographTitle is using it also
> issue #693: Added k4 relations for oldPrint volume and monographTitle

- proarc-common/src/main/java/cz/cas/lib/proarc/common/object/ndk/RdaRules.java
Pokud se stáhne záznam z katalogu s nevyplněným polem pro RecordInfo:DescriptionStandard, je defualtně nastavena hodnota AACR
> issue #694: set default value in DescriptionStandard

- .travis.yml
- fedora-test.yml
- pom.xml
- proarc-common/pom.xml
- proarc-common/src/test/java/cz/cas/lib/proarc/common/fedora/SearchViewTest.java
Nastavil jsem integrační testy pro Fedoru na Travisu. Bohužel se některé testy ignorují, protože docker volumy umí pouze Travis Enterprise. Ale i takto je to myslím lepší než nic (a stejně v budoucnu zmigrujeme na Fedoru 4 a bude to zase všechno jinak).
Jeden test neprochází
```
testResolveObjectLabel(cz.cas.lib.proarc.common.fedora.SearchViewTest)  Time elapsed: 3.223 s  <<< FAILURE!
org.junit.ComparisonFailure: expected:<1, Title[ ]Page> but was:<1, Title[]Page>
at cz.cas.lib.proarc.common.fedora.SearchViewTest.testResolveObjectLabel(SearchViewTest.java:99)
```
Souvisí to s https://github.com/proarc/proarc/commit/1fcbec0e8d4718e4fbc61e433f333c1004a19bc7 a se změnou resourcebundlu modsPageTypes.properties. Např. klíč TitlePage->titlepage.
Rozbilo to testy. Nevím, jestli to mohlo rozbít i …
> Travis - Fedora integration tests

- proarc-common/pom.xml
- proarc-common/src/test/java/cz/cas/lib/proarc/common/jobs/BatchImportJobTest.java
Po proběhnutí testu se nyní Quartz Scheduler vypne, aby neovlivňoval další testy.
To se přesně dělo, potom občas padnul test TransformerTests, který detekuje, že nedojde souběžně k síťovému spojení. Používá na to custom ProxySelector (který zavolá JVM při každém síťovém požadavku).
viz https://github.com/proarc/proarc/blob/master/proarc-common/src/test/java/cz/cas/lib/proarc/common/xml/TransformersTest.java#L76
_____
@jkremlacek Scheduler jsem udělal statický, aby byl pro celý soubor testů pouze jeden. Nejsem si jistý, jestli jsi to tak zamýšlel, ale jinak padal ten poslední test (normálně se vytvořil a nevyhodil očekávanou výjimku).
> BatchImportJobTest correct teardown

- proarc-common/src/main/java/cz/cas/lib/proarc/common/workflow/model/TaskParameter.java
- proarc-common/src/main/java/cz/cas/lib/proarc/common/workflow/profile/SetParamDefinition.java
- proarc-webapp/src/main/java/cz/cas/lib/proarc/webapp/client/widget/workflow/WorkflowNewJobView.java
Možná po nějakém updatu smartgwt se přestal posílat changeddataevent při refreshi stránky - menu s modely se tedy vůbec neplnilo. Takže jsem doplnil plnění i na DataArrivedEvent.
+ přidal jsem trim na parametry z workflow.xml, abych předešel problému (který se v KNAV přesně stal), že uživatel nadefinguje param.export4K jako číslo, ale potom nastaví parametr takto:
```
<setParam paramRef="param.exportK4">
</setParam>
```
do value se potom házel whitespace string (např \n\t) a validace čísla neprošla.
> issue #759: RDflow menu nového záměru

- proarc-common/src/main/java/cz/cas/lib/proarc/common/json/JsonUtils.java
Mělo by řešit problém s načítáním publikací se speciálními znaky v metadatech.
> issue #806: enable unquoted control characters in JSON parser

- proarc-webapp/src/main/java/cz/cas/lib/proarc/webapp/client/widget/mods/NdkArticleForm.java
- proarc-webapp/src/main/java/cz/cas/lib/proarc/webapp/client/widget/mods/NdkChapterForm.java
Do formuláře NdkArticle a NdkChapter přidán nový elemnt <part:extent:unit>, který slouží k zapsani podřazených stránek. 
Více informací v issue #774.
> issue #774: add element part:extent:unit in NdkArticle and NdkChapter

- proarc-common/pom.xml
- proarc-premis/pom.xml
Nejspíš jde o artefakt předchozí verze, nicméně master větev kvůli tomu nejde zbuildit.
Místo tvrdého odkazu na `3.5-SNAPSHOT` nahrazeno proměnnou na `project.version`.
> Oprava verzování v pom.xml souborech
